packages:
  - name: email
    actions:
      - name: birthday
        runtime: 'python:default'
        triggers:
          - name: 'email-trigger'
            sourceType: scheduler
            sourceDetails:
              cron: '0/2 * * * *'
